# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$O1GIQHAkDjxUonGytsRDCOZsIKFu40om5s3GI6IXQ6OSnjV1zVdvm
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$O9L9xRTROgOXsz3EgT.UDeLlbt67.BdbofD0U00J6Q/HsCcVtdoKq
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider: in_memory
            switch_user: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   logout
                target: homepage

    access_control:
      - { path: ^/login, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
      - { path: ^/activity, roles: 'ROLE_USER' }
      - { path: ^/projects, roles: 'ROLE_USER' }
      - { path: ^/issues, roles: 'ROLE_USER' }
      - { path: ^/user_comment, roles: 'ROLE_USER' }
      - { path: ^/user_comment, roles: 'ROLE_USER' }
